Ah não! Algo deu errado e lá vem o Bugginho de novo.
A issue de número <a href="{{ issue.html_url|raw }}" target="_blank">#{{ issue.number }}</a>, do repositório <a href="{{ repositorio.html_url|raw }}" target="_blank">{{ repositorio.name }}</a>acaba de ser reaberta pelo usuário <a href="{{ user.html_url|raw }}" target="_blank">@{{ user.login }}</a>
