Ah não! Algo deu errado e lá vem o Bugginho de novo.

A issue de número *#{{ issue.number }} - {{ issue.title }}*({{ issue.html_url|raw }}), do repositorio *{{ repositorio.name }}* acaba de ser reaberta pelo usuário *@{{ user.login }}*
----